version: '2'

services:
  odoo_db:
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - 'odoo_db_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=odoo_admin
      - POSTGRESQL_DATABASE=odoo
      - POSTGRESQL_PASSWORD=admin123
  odoo:
    image: bitnami/odoo:17
    ports:
      - '8069:8069'
    volumes:
      - 'odoo_data:/bitnami/odoo'
    depends_on:
      - odoo_db
    environment:
      - ODOO_EMAIL=admin@example.com
      - ODOO_PASSWORD=admin123
      - ODOO_DATABASE_HOST=odoo_db
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=odoo_admin
      - ODOO_DATABASE_NAME=odoo
      - ODOO_DATABASE_PASSWORD=admin123
  
  nextcloud_db:
    image:  mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud_admin
      - MARIADB_PASSWORD=admin123
      - MARIADB_ROOT_PASSWORD=admin123
  nexcloud:
    image: nextcloud
    ports:
      - '8080:80'
    volumes:
      - 'nextcloud_data:/var/www/html'
    depends_on:
      - nextcloud_db
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_admin
      - MYSQL_PASSWORD=admin123
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
  
volumes:
  odoo_db_data:
    driver: local
  odoo_data:
    driver: local
  nextcloud_db_data:
    driver: local
  nextcloud_data:
    driver: local